pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node
    commands:
      - npm install

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: false
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  frontend:
    image: node:8
    commands:
      - npm test
